
export const APP_CONFIG = {
  VISUAL_START_HOUR: 0,
  VISUAL_END_HOUR: 24,
  DEFAULT_DURATION_MINUTES: 60,
  MIN_DURATION_MINUTES: 15,
  DEFAULT_LEAD_TIME_HOURS: 1,
  DATE_FORMAT: 'yyyy-MM-dd',
  TIME_FORMAT: 'HH:mm',

  // API Config
  API_BASE_URL: 'http://192.168.1.100:8082/api'
};
